version: "2.0"

services:
  circleci-meteor:
    container_name: circleci-meteor
    image: classcraft/circleci-meteor:${METEOR}
    build:
      context: .
      args:
        CYPRESS: ${CYPRESS}
        METEOR: ${METEOR}
        NODE: ${NODE}
